### ISSUE TITLE
use case?

### ISSUE THREAD

**Issue by turnermm** [turnermm/ckgdoku#1]
Have you put this into effect with a user group yet?  I would like to make it mainstream when possible.

**Comment by stevenmg** [comment]
I have not. Unfortunately this project is being delayed due to other more high priority projects coming up. Once I have it live I'll let you know how it goes.

**Comment by turnermm** [comment]
I will post it to the versions section of the ckgedit plugin page with a description.  And I would like to credit you, if that's ok.

**Comment by stevenmg** [comment]
Sure, that'd be great. Hopefully a few people pick it up and give some feedback :+1:

**Comment by stevenmg** [comment]
@turnermm Due to some new requirements for my documentation project I am changing course, and rather than using DokuWiki I am building on a Wordpress based system. This means I will no longer be working on this plugin. I hope my contributions so far have been useful, and of course you are free to use them as you like.

**Comment by turnermm** [comment]
Sorry to lose you but thanks for your contributions.
