### ISSUE TITLE
Update problem with changed URL

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgdoku#4]
Hi,

after activating the new ckgdoku plugin from https://www.dokuwiki.org/plugin:ckgdoku there is a message that the URL has changed:
![grafik](https://cloud.githubusercontent.com/assets/1800472/24105575/96236ff6-0d85-11e7-9030-d13bf01c1401.png)

Best regards
Juergen

**Comment by turnermm** [comment]
You will always get this message, because you are installing an alternate version of ckgedit (ckgdoku) which has a different download link from ckgedit.  It is installed by necessity in the ckgedit plugin directory and so appears to the extension manager to be ckgedit and not ckgdoku.   For this reason you can't use the update button for ckgedit/ckgdoku, because it will overwrite ckgdoku with ckgedit.

**Comment by turnermm** [comment]
I am working to separate ckgedit from ckgdoku so that it will be simple to update ckgdoku using the extension manager.  I created a new branch of ckgdoku: 
    https://github.com/turnermm/ckgdoku/archive/trans.zip
When I am satisfied that this branch is without errors, I will merge it with the master branch and you will then be able to update using the update button.  If you have the time, perhaps you can try it out.

**Comment by turnermm** [comment]
ckgdoku is now a separate plugin, using its own directory and no longer loads into the ckgedit directory.  See: https://www.dokuwiki.org/plugin:ckgdoku
