### ISSUE TITLE
Additional File Browsers and JQuery UI use

### ISSUE THREAD

**Issue by CornHead764** [turnermm/ckgdoku#60]
After some extended use of this plugin, I think it would really benefit from the ability to add additional file browsers to it. Currently, it's just the implementation of ckeditor, which is great, however forces the use of fckeditor's old 1998 style editor (and ckgdoku gives the option for linkwiz...). Would it be feasible to adjust the code to allow for additional file browsers to be added with just a minor config change? Or perhaps even a config option that's auto generated from a directory structure. In addition to this, the standard popup style window is a bit dated, and could also benefit from a change to a jquery ui dialog instead. In the case of a few different file browsers, most notably my favorite, elFinder, this change would allow for many new features, as well as a very welcomed UI update.

**Comment by turnermm** [comment]
The CKEditor is open source, like dokuwiki, and so free to use and modify.  When the CKEditor people updated their editor, they specifically removed the file browser in order to offer separately a proprietary file browser for which they can charge various fees.  If this fits in with your needs you can go to their site and investigate this option.  I've never done this.  If you look into it and see a way to integrate a browser of your choice, I'd be happy to hear about it, but it's not something I want to get into on my own.
